package generator;

public class GeneratorUtil {
	public static final String NEW_LINE = "\n";
	public static final String SEMICOLON = ";";
	public static final String TODO_PLACEHOLDER = "// TODO auto-generated by CodeGenerator";
	public static final String TODO_APPEND_PLACEHOLDER = "// TODO auto-appended by CodeGenerator";
	public static final String END_PLACEHOLDER = "// end";

	public static final String PACKAGE = "package";
	public static final String IMPORT = "import";
	public static final String STATIC = "static";
	public static final String ABSTRACT = "abstract";
	public static final String FINAL = "final";
	public static final String CLASS = "class";
	public static final String INTERFACE = "interface";
	public static final String EXTENDS = "extends";
	public static final String IMPLEMENTS = "implements";
	public static final String RETURN = "return";

	public static String generateIndent(int level) {
		String indent = "";
		for(int i = 0; i < level*4; i++) {
			indent += " ";
		}
		
		return indent;
	}
}
